defaults:  
  - _self_  
  - override hydra/job_logging: disabled  
  - override hydra/hydra_logging: disabled  

training:
  epochs: 150             
  batch_size: 32
  lr: 1e-4
  save_dir: "checkpoints"
  num_workers: 4
  grad_clip: 0.1
  noise_std: 0.01         
  
  curriculum:
    max_rollout_steps: 12 
    start_rollout_steps: 5
    increase_every_epochs: 15        
    teacher_forcing_decay_epochs: 100 # === 修改：延长衰减周期，给模型充分的过渡时间 ===

  loss_weights:
    pos: 2.0
    rigid: 2.0
    energy: 0.1

model:
  num_points: 64
  latent_dim: 128
  num_global_vectors: 1
  context_dim: 3
  history_len: 3          

dataset:
  train_path: "data/sapien_train_seq.pt"
  val_path: "data/sapien_val_seq.pt"

logger:
  project_name: "se3-world-model"
  run_name: "seq2seq_noise_injection" 
  use_wandb: true
  use_tensorboard: true
